version: '3.8'

networks:
  lightning-net:
    name: lightning-net
    driver: bridge

volumes:
  alice_data:
  bob_data:
  carol_data:
  dave_data:
  emma_data:
  frank_data:

services:
  alice:
    container_name: ${COMPOSE_PROJECT_NAME}_alice
    image: bitcoinstack/lnd:0.10.0-alpine
    restart: unless-stopped
    networks:
      lightning-net:
        aliases:
          - ${ALICE_HOST}
    command: [
      "--noseedbackup",
      "--alias=alice",
      "--listen=0.0.0.0:${ALICE_PORT}",
      "--rpclisten=0.0.0.0:${ALICE_RPC_PORT}",
      "--restlisten=0.0.0.0:${ALICE_REST_PORT}",
      "--tlsextradomain=${ALICE_HOST}",
      "--tlsextraip=0.0.0.0",
      "--autopilot.allocation=0",
      "--bitcoin.active",
      "--bitcoin.regtest",
      "--bitcoin.node=bitcoind",
      "--bitcoind.rpchost=${BITCOIN_HOST}:${BITCOIN_RPC_PORT}",
      "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoind.rpcpass=${BITCOIN_RPC_PASSWORD}",
      "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}",
      "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    depends_on:
      - bitcoin
    ports:
      - "127.0.0.1:${ALICE_RPC_PORT}:${ALICE_RPC_PORT}"
      - "127.0.0.1:${ALICE_REST_PORT}:${ALICE_REST_PORT}"
    volumes:
      - alice_data:/home/lnd/.lnd

  bob:
    container_name: ${COMPOSE_PROJECT_NAME}_bob
    image: bitcoinstack/lnd:0.10.0-alpine
    networks:
      lightning-net:
        aliases:
          - ${BOB_HOST}
    restart: unless-stopped
    command: [
      "--noseedbackup",
      "--alias=bob",
      "--listen=0.0.0.0:${BOB_PORT}",
      "--rpclisten=0.0.0.0:${BOB_RPC_PORT}",
      "--restlisten=0.0.0.0:${BOB_REST_PORT}",
      "--tlsextradomain=${BOB_HOST}",
      "--tlsextraip=0.0.0.0",
      "--autopilot.allocation=0",
      "--accept-keysend",
      "--bitcoin.active",
      "--bitcoin.regtest",
      "--bitcoin.node=bitcoind",
      "--bitcoind.rpchost=${BITCOIN_HOST}:${BITCOIN_RPC_PORT}",
      "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoind.rpcpass=${BITCOIN_RPC_PASSWORD}",
      "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}",
      "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    depends_on:
      - bitcoin
    ports:
      - "127.0.0.1:${BOB_RPC_PORT}:${BOB_RPC_PORT}"
      - "127.0.0.1:${BOB_REST_PORT}:${BOB_REST_PORT}"
    volumes:
      - bob_data:/home/lnd/.lnd

  carol:
    container_name: ${COMPOSE_PROJECT_NAME}_carol
    image: bitcoinstack/clightning:0.8.2.1-alpine
    networks:
      lightning-net:
        aliases:
          - ${CAROL_HOST}
    command: [
      "--alias=carol",
      "--network=regtest",
      "--large-channels",
      "--addr=0.0.0.0:${CAROL_PORT}",
      "--bitcoin-cli=/bitcoin/bitcoin-cli",
      "--bitcoin-datadir=/bitcoin",
      "--bitcoin-rpcconnect=${BITCOIN_HOST}",
      "--bitcoin-rpcport=${BITCOIN_RPC_PORT}",
      "--bitcoin-rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoin-rpcpassword=${BITCOIN_RPC_PASSWORD}"
    ]
    depends_on:
      - bitcoin
    volumes:
      - carol_data:/home/clightning/.lightning
      - ./clightning/plugins:/home/clightning/.lightning/plugins
      - bitcoin_shared:/bitcoin

  dave:
    container_name: ${COMPOSE_PROJECT_NAME}_dave
    image: bitcoinstack/clightning:0.8.2.1-alpine
    networks:
      lightning-net:
        aliases:
          - ${DAVE_HOST}
    command: [
      "--alias=dave",
      "--network=liquid-regtest",
      "--addr=0.0.0.0:${DAVE_PORT}",
      "--large-channels",
      "--bitcoin-cli=/elements/elements-cli",
      "--bitcoin-datadir=/elements",
      "--bitcoin-rpcconnect=${ELEMENTS_HOST}",
      "--bitcoin-rpcport=${ELEMENTS_RPC_PORT}",
      "--bitcoin-rpcuser=${ELEMENTS_RPC_USER}",
      "--bitcoin-rpcpassword=${ELEMENTS_RPC_PASSWORD}"
    ]
    depends_on:
      - elements
    volumes:
      - dave_data:/home/clightning/.lightning
      - elements_shared:/elements

  emma:
    container_name: ${COMPOSE_PROJECT_NAME}_emma
    image: bitcoinstack/clightning:0.8.2.1-alpine
    networks:
      lightning-net:
        aliases:
          - ${EMMA_HOST}
    command: [
      "--alias=emma",
      "--network=liquid-regtest",
      "--addr=0.0.0.0:${EMMA_PORT}",
      "--large-channels",
      "--bitcoin-cli=/elements/elements-cli",
      "--bitcoin-datadir=/elements",
      "--bitcoin-rpcconnect=${ELEMENTS_HOST}",
      "--bitcoin-rpcport=${ELEMENTS_RPC_PORT}",
      "--bitcoin-rpcuser=${ELEMENTS_RPC_USER}",
      "--bitcoin-rpcpassword=${ELEMENTS_RPC_PASSWORD}"
    ]
    depends_on:
      - elements
    volumes:
      - emma_data:/home/clightning/.lightning
      - elements_shared:/elements

  frank:
    container_name: ${COMPOSE_PROJECT_NAME}_frank
    image: dkrm/eclair:latest
    networks:
      lightning-net:
        aliases:
          - ${FRANK_HOST}
    command: >-
        bash eclair-node/bin/eclair-node.sh
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Xmx512m
        -Declair.headless=true
        -Declair.printToConsole=true
        -Declair.chain=regtest
        -Declair.datadir=/data
        -Declair.node-alias=frank
        -Declair.server.port=${FRANK_PORT}
        -Declair.bitcoind.host=${BITCOIN_HOST}
        -Declair.bitcoind.rpcport=${BITCOIN_RPC_PORT}
        -Declair.bitcoind.rpcuser=${BITCOIN_RPC_USER}
        -Declair.bitcoind.rpcpassword=${BITCOIN_RPC_PASSWORD}
        -Declair.bitcoind.zmqtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}
        -Declair.bitcoind.zmqblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}
        -Declair.api.enabled=true
        -Declair.api.port=${FRANK_REST_PORT}
        -Declair.api.password=password
        -Declair.api.binding-ip=0.0.0.0
    ports:
      - "127.0.0.1:${FRANK_REST_PORT}:${FRANK_REST_PORT}"
    depends_on:
      - bitcoin
    volumes:
      - frank_data:/data

  subscriber:
    container_name: ${COMPOSE_PROJECT_NAME}_subscriber
    image: bitcoinstack/subscriber:0.1
    networks:
      - lightning-net
    restart: unless-stopped
    command: ['node', 'subscriber.js']
    depends_on:
      - alice
    environment:
      - ALICE_HOST
      - ALICE_RPC_PORT
    volumes:
      - ./node/app:/usr/src/app
      - alice_data:/lnd:ro
